travis:
  secure:
    BINSTAR_TOKEN: SyIAa3zBnJenp7dwvV52YwIo1F2ZD13/0cxHHgxdx9weurZIVYEyDbLncmbHksrU3HgMEloQhPn9PDARHNSee0DFemIRF2rDktufxpdWcABH7aKBmdWNUFy/KxF4sbAetlXpzzbUwHey/ShLbHf1bJpBoxfTqZ+Qo+cY2R/aqamD6hD5sl3BBanET9m7hFcc/jz3Hb05xe+XQBX61x6fO4Yl4PTnSuLdZHAjDrVqvlqAzNl7bp4ykRSeZ98PZNNtLntxb83GLv+h+xbd5TZM/SCDYsCZpQLQyJKW9yUvxYJwvmgvEMLc0G6KwgW6MSlkr4fZCWA/VBisyUuS09Ckii996/XFfKF86MuzXfhWpQhITkWXtp+u+tuHl0yMwaZ9MjyCnNUu5NkDtcXKgMswTT1U88v2QQu5leACEwp5g7q1dXQflT6BHAx93LksyULc9caTLGgiuln7r7jI1LD+4enAcrSjne+6Krs5U+eyerYD6mXmVlUG3s2xk01w/oejQ+2sHnvYAsnZjW1fC9POeoE8VP+TN6VrafkhS1QBbaEFb6ss1ugaupJL1mc3xP9oVwuHMKNu2QLLK+Ap9TQ+vOfAzSlF6i2EQaNxBE9BSZ+sJ+yDxXivD/4B/bqXNnH0RSQnNGpdFDLgEMWPqfp5EW7dMVEKDZTIUFxm+W9+Ook=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
